### ISSUE TITLE
Partials might not be e.g. *.html but *.html.hbs

### ISSUE THREAD

**Issue by devinus** [superwolff/metalsmith-layouts#46] opened 2015-09-04 01:53 UTC
https://github.com/superwolff/metalsmith-layouts/blob/master/lib/helpers/read-partials.js#L34

This assumes a single extension, but a partial might need to be e.g. `nav.html.hbs`

**Comment by ismay** [comment] 2015-09-04 06:33
That's true. But it doesn't really matter how much extensions you have, it'll just remove the last one (if there are any) for simpler partial names. So your partial name will just be `nav.html`.

I'll close this since this is intended behaviour, but let me know if you have further questions!

**Comment by devinus** [comment] 2015-09-04 16:06
@ismay Unfortunately templating engines such as e.g. Handlebars don't support `.` in partial names.

**Comment by devinus** [comment] 2015-09-04 16:06
Perhaps a `partialExtension` option could be supported?

**Comment by ismay** [comment] 2015-09-04 18:18
Yeah that's true. A `partialExtension` option would be a good idea. And when no `partialExtension` option's passed it won't remove anything from the partial's name. Do you have time to submit a PR?

**Comment by ismay** [comment] 2016-01-31 16:56
@devinus Btw., could you elaborate on why you'd want to use multiple extensions? I don't see a reason for using .html.hbs instead of .hbs.

**Comment by ismay** [comment] 2016-02-04 13:10
See https://github.com/superwolff/metalsmith-in-place/pull/33. Multiple extensions for templates seems to be a rails practice. There's no need for multiple extensions with this tool, and not removing all parts of the name following a dot would also prevent problems for files with multiple dots in their name.

Feel free to reopen if there is a valid need for files with multiple extensions that I've overlooked.

**Closed by ismay** 2016-02-04 13:10 UTC

**Comment by devinus** [comment] 2016-02-04 17:08
What is a `*.hbs` file? Is it Handlebars wrapping plain text? XML? The reason people use e.g. `*.html.hbs` is so that asset pipelines and code editors know what the resulting file extension should be (just chop off the `hbs` extension).

**Comment by ismay** [comment] 2016-02-04 18:06
The double extension is a rails convention. There's no need for it with metalsmith as metalsmith doesn't rename or process based on the the last extension, and I don't know of any metalsmith plugins that do.

The editors that I know treat .hbs as an html file with handlebars syntax and correctly highlight both.
